In [1]:
import numpy as np

In [2]:
np.array

<function numpy.array>

In [3]:
mylist0 = [0,1,2,3,4,5]

In [4]:
myna = np.array(mylist0)

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.random.random(5)

array([0.0668988 , 0.03155586, 0.8752578 , 0.08360544, 0.89052364])

In [7]:
list1 = [0,1,2,3,4,5]
list2 = [0,1,2,3,4,5]
nplist1 = np.array(list1)
nplist2 = np.array(list2)
nplist1+nplist2


array([ 0,  2,  4,  6,  8, 10])

In [8]:
nplist1*nplist2

array([ 0,  1,  4,  9, 16, 25])

In [9]:
nplist3 = np.array([1,2,3,4,5])

In [10]:
type(nplist3)

numpy.ndarray

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.random.randn(4,4)

array([[-2.61105286e-01,  9.39668252e-01, -6.71563822e-04,
        -7.02717008e-01],
       [-1.25198607e+00, -7.87451037e-01,  1.75787813e+00,
         1.02546549e+00],
       [ 3.15487469e-01, -1.51008598e+00,  2.79203578e+00,
         5.91162855e-02],
       [ 3.17549511e-01, -2.88103677e+00,  3.86270066e-02,
        -9.09540915e-01]])

In [13]:
matrix =np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [14]:
np.ndim(matrix)

2

In [15]:
np.shape(matrix)

(3, 3)

In [16]:
nplist3[::-1]

array([5, 4, 3, 2, 1])

In [17]:
nplist3[1:4]

array([2, 3, 4])

In [19]:
random_list = np.random.randint(1,30,5)

In [41]:
mtx1 = np.array([[10,10],
                 [20,20]]) #2x2

mtx2 =  np.array([[30,30],
                 [40,40]]) #2x2


mtx3 =  np.array([[30,30]]) #1x2

mtx4 = np.array([[1,2,3,4,5,6],
                 [1,2,3,4,5,6],
                 [1,2,3,4,5,6]]) #3x6

In [29]:
mtx1+mtx2

array([[40, 40],
       [60, 60]])

In [31]:
mtx1+mtx3   #Broadcast -benzeterek tamamlıyor- 

array([[40, 40],
       [50, 50]])

In [32]:
mtx1* mtx2

array([[300, 300],
       [800, 800]])

In [44]:
mtx1 * mtx3 # Thats not a real matrix product . it multiply all values each other not rows and columns

array([[300, 300],
       [600, 600]])

In [39]:
mtx1*mtx4 # sonunda error kankam

ValueError: operands could not be broadcast together with shapes (2,2) (3,6) 

In [43]:
mtx1.dot(mtx2) #Real matrix product

array([[ 700,  700],
       [1400, 1400]])

In [47]:
newmat = np.random.randint(1,100,20)
newmat

array([16, 89, 24, 93,  7, 50, 41, 54, 31, 30, 98, 89, 43, 15,  9, 58,  1,
       12, 86, 25])

In [48]:
newmat[newmat>40]

array([89, 93, 50, 41, 54, 98, 89, 43, 58, 86])

In [55]:
#transpose and reshape
transposemat = np.array([[1,2,3,4],
                         [3,4,5,6],
                         [5,6,7,8]]) #3x4

In [54]:
transposemat.transpose()

array([[1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [56]:
transposemat.reshape(2,6)

array([[1, 2, 3, 4, 3, 4],
       [5, 6, 5, 6, 7, 8]])

In [57]:
# math equations
# 2x+3y=8
# 5x+7y=19

In [62]:
#Coefficient
A = np.array([[2,3],[5,7]])
#const
B = np.array([8,19])

In [63]:
SOL =np.linalg.solve(A,B)
SOL

array([1., 2.])